Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 6
Rules claiming more threads will be scaled down.
Singularity containers: ignored
Job counts:
	count	jobs
	1	align_mni_rigid
	1	all
	32	featureExtract_coarse
	1	fid_tform_mni_rigid
	1	fsl_to_ras
	36

[Sun Jul 26 22:56:16 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-01_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-01_registration.done
    jobid: 3
    wildcards: afid_num=01

[Sun Jul 26 22:56:16 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-07_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-07_registration.done
    jobid: 9
    wildcards: afid_num=07

[Sun Jul 26 22:56:16 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-14_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-14_registration.done
    jobid: 16
    wildcards: afid_num=14

[Sun Jul 26 22:56:16 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-22_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-22_registration.done
    jobid: 24
    wildcards: afid_num=22

[Sun Jul 26 22:56:16 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-29_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-29_registration.done
    jobid: 31
    wildcards: afid_num=29

[Sun Jul 26 22:56:16 2020]
rule featureExtract_coarse:
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-08_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-08_registration.done
    jobid: 10
    wildcards: afid_num=08

[Sun Jul 26 22:56:23 2020]
Error in rule featureExtract_coarse:
    jobid: 10
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-08_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-08_registration.done

RuleException:
CalledProcessError in line 61 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpmn29h7i6.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 61, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Sun Jul 26 22:56:23 2020]
Error in rule featureExtract_coarse:
    jobid: 3
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-01_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-01_registration.done

RuleException:
CalledProcessError in line 61 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpzai4pd1k.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 61, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Sun Jul 26 22:56:25 2020]
Error in rule featureExtract_coarse:
    jobid: 16
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-14_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-14_registration.done

RuleException:
CalledProcessError in line 61 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpox3_chk9.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 61, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Sun Jul 26 22:56:25 2020]
Error in rule featureExtract_coarse:
    jobid: 24
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-22_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-22_registration.done

RuleException:
CalledProcessError in line 61 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpe4xvc2dp.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 61, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Sun Jul 26 22:56:25 2020]
Error in rule featureExtract_coarse:
    jobid: 9
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-07_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-07_registration.done

RuleException:
CalledProcessError in line 61 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmpbiiptvzx.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 61, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
[Sun Jul 26 22:56:25 2020]
Error in rule featureExtract_coarse:
    jobid: 31
    output: /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-29_desc-coarse_features.npy, /media/veracrypt6/projects/autofids/data/OASIS/deriv/features/afid-29_registration.done

RuleException:
CalledProcessError in line 61 of /home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk:
Command 'set -euo pipefail;  /usr/bin/python3 /home/greydon/Documents/GitHub/Auto-afids/.snakemake/scripts/tmp5tsuwzvk.data_store.py' returned non-zero exit status 1.
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2168, in run_wrapper
  File "/home/greydon/Documents/GitHub/Auto-afids/workflow/rules/mniTransform.smk", line 61, in __rule_featureExtract_coarse
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/greydon/.local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2199, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/greydon/Documents/GitHub/Auto-afids/.snakemake/log/2020-07-26T225616.177477.snakemake.log
